# Example eval config
base_model: "Qwen/Qwen3-0.6B"
adapter: "runs/sft/qwen3-0.6b/local-smoke/checkpoint-600"  # Optional, remove for base model eval
prompts: "evals/prompts/safety_basic.json"
eval_fn: "evals.judges.eval_fns:check_refusal"

# Generation params (all optional, defaults shown)
batch_size: 4
max_new_tokens: 256
temperature: 0.7  # Set to 0 for greedy decoding

# Output settings (optional)
run_id: "sft-checkpoint-600"  # Defaults to adapter parent dir name
output_dir: "runs/sft/qwen3-0.6b/local-smoke/evals"
